# Generated by Django 5.2.5 on 2025-09-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
