# Generated by Django 4.2.23 on 2025-11-23 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accesorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendedores/perfiles/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("contacto", models.CharField(blank=True, max_length=50, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendedores/tiendas/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("color_principal", models.CharField(blank=True, max_length=30)),
                ("color_secundario", models.CharField(blank=True, max_length=30)),
                ("tema_visual", models.CharField(blank=True, max_length=30)),
                (
                    "metodos_pago",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Transferencia, PayPal, Efectivo",
                        max_length=200,
                    ),
                ),
                ("politica_envios", models.TextField(blank=True)),
                ("stock_inicial", models.PositiveIntegerField(default=0)),
                (
                    "categorias",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Ropa, Accesorios, Decoración",
                        max_length=200,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.sellerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo_lana",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("algodon", "Algodón"),
                            ("lana", "Lana"),
                            ("acrilico", "Acrílico"),
                            ("mezcla", "Mezcla"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "accesorios_favoritos",
                    models.ManyToManyField(blank=True, to="productos.accesorio"),
                ),
                (
                    "colores_favoritos",
                    models.ManyToManyField(blank=True, to="productos.color"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("material", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="imagenProductos/"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
