# Generated by Django 5.2.5 on 2025-11-24 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
