# Generated by Django 4.2.23 on 2025-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_lana',
            field=models.CharField(blank=True, choices=[('algodon', 'Algodón'), ('lana', 'Lana'), ('acrilico', 'Acrílico'), ('mezcla', 'Mezcla')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='accesorios_favoritos',
            field=models.ManyToManyField(blank=True, to='productos.accesorio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='colores_favoritos',
            field=models.ManyToManyField(blank=True, to='productos.color'),
        ),
    ]
