# Generated by Django 5.2.5 on 2025-09-10 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_accesorio_color_profile_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='vendedores/perfiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='vendedores/tiendas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('color_principal', models.CharField(blank=True, max_length=30)),
                ('color_secundario', models.CharField(blank=True, max_length=30)),
                ('tema_visual', models.CharField(blank=True, max_length=30)),
                ('metodos_pago', models.CharField(blank=True, help_text='Ej: Transferencia, PayPal, Efectivo', max_length=200)),
                ('politica_envios', models.TextField(blank=True)),
                ('stock_inicial', models.PositiveIntegerField(default=0)),
                ('categorias', models.CharField(blank=True, help_text='Ej: Ropa, Accesorios, Decoración', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.sellerprofile')),
            ],
        ),
    ]
