# Generated by Django 5.2.5 on 2025-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenProductos/'),
        ),
    ]
