# Generated by Django 4.2.23 on 2025-11-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_product_image"),
        ("productos", "0006_product_imagen"),
    ]

    operations = []
