# Generated by Django 4.2.23 on 2025-11-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_merge_0002_product_image_0006_product_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
